### ISSUE TITLE
Message d'erreur [Area Effect Cloud]

### ISSUE THREAD

**Issue by MathsYeux** [MrBurdy/More-Machinery-Features#1]
> 
![Uploading IMG_20211002_013833_1.jpg…]()

**Comment by MrBurdy** [comment]
Bonjour, désolé je n'arrives pas à voir la photo/screen.

**Comment by MrBurdy** [comment]
Je viens de voir le problème, je l'ai corrigé, c'est la dernière mise à jour pour la 1.16, cette version ne sera plus supportée.

I just saw the problem, I fixed it, this is the last update for 1.16, this version will not be supported anymore.

**Comment by MathsYeux** [comment]
D'accord, merci beaucoup
Avec un pote on a commencé une survie modée avec ce datapack en plus, et le
datapack est génial, on s'est tapé un fou rire monstrueux avec le cd de
rick asley et on a fait tout ce qui était possible dedans (sauf les
mystères on a que 1 et 3)
Merci pour ce datapack ;)

**Comment by MrBurdy** [comment]
De rien :)
Bonne partie à vous tous ;)

**Comment by MrBurdy** [comment]
De rien :)
Bonne partie à vous tous ;)
