### ISSUE TITLE
tresor finder doesn't search under y=0

### ISSUE THREAD

**Issue by Friedrich-K** [MrBurdy/More-Machinery-Features#3]
I am assuming that this is not intended.
I fixed it by modifying "More+Machinery++Features+Datapack\data\mmaf\functions\main\player\items\tresor_finder\check.mcfunction"
Just replace line 27 with "execute if entity @s[scores={MBbqtt=..318}] positioned ~ ~-1 ~ run function mmaf:main/player/items/tresor_finder/check"

**Comment by MrBurdy** [comment]
Hello, thank you for reporting this problem, it was simply designed for the old height of the world.
The problem has been fixed, the update will be released soon and will correct the problem.
Thank you again for the feedback and good continuation :)
