### ISSUE TITLE
download for datapack url not found

### ISSUE THREAD

**Issue by wolfenergistics** [MrBurdy/More-Machinery-Features#6]
Hello and sorry to bother you but the datapack link isn't working,
best regards

**Comment by Tacos-5976** [comment]
here is the datapack link: https://www.curseforge.com/minecraft/texture-packs/more-machinery-features/download/4064372

and resource pack: https://www.curseforge.com/minecraft/texture-packs/more-machinery-features-resource-pack/download/4064373
